### ISSUE TITLE
zola serve panic

### ISSUE THREAD

**Issue by flyingicedragon** [Keats/gutenberg#2464]
# Bug Report

I'm newer to zola. I met this panic when I just tried the Overview. Anything I missed?

## Environment

Zola version: both 0.18.0 and 0.17.2

Operating System: Debian GNU/Linux 12

## Expected Behavior

Start the Zola development server.

## Current Behavior

<details>
<summary>RUST_BACKTRACE=1</summary>

```shell
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 0 pages (0 orphan) and 0 sections
Done in 19ms.

thread 'main' panicked at src/cmd/serve.rs:437:59:
called `Result::unwrap()` on an `Err` value: Io(Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" })
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

<details>
<summary>RUST_BACKTRACE=full</summary>

```shell
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 0 pages (0 orphan) and 0 sections
Done in 21ms.

thread 'main' panicked at src/cmd/serve.rs:437:59:
called `Result::unwrap()` on an `Err` value: Io(Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" })
stack backtrace:
   0:     0x55eb65ee58ef - <unknown>
   1:     0x55eb6575af5c - <unknown>
   2:     0x55eb65eaf22d - <unknown>
   3:     0x55eb65ee6e6e - <unknown>
   4:     0x55eb65ee6a53 - <unknown>
   5:     0x55eb65ee7a09 - <unknown>
   6:     0x55eb65ee753c - <unknown>
   7:     0x55eb65ee7496 - <unknown>
   8:     0x55eb65ee7481 - <unknown>
   9:     0x55eb654a4214 - <unknown>
  10:     0x55eb654a4782 - <unknown>
  11:     0x55eb65590284 - <unknown>
  12:     0x55eb655a296d - <unknown>
  13:     0x55eb655484c3 - <unknown>
  14:     0x55eb655af335 - <unknown>
  15:     0x7fbd0e3e524a - <unknown>
  16:     0x7fbd0e3e5305 - __libc_start_main
  17:     0x55eb6550f3c1 - <unknown>
  18:                0x0 - <unknown>
```

</details>

## Step to reproduce

```shell
zola init zola-test
cd zola-test
zola serve
```

**Comment by Keats** [comment]
Hm never seen that one before and cannot reproduce on my machine :/
What's the content of the zola-test directory (with `tree`)

**Comment by flyingicedragon** [comment]
> Hm never seen that one before and cannot reproduce on my machine :/ What's the content of the zola-test directory (with `tree`)

Zola-test directory was created by `zola init`. I didn't have this directory before.
```
zola-test
├── config.toml
├── content
├── public
├── sass
├── static
├── templates
└── themes
```

I also tried this on another Debian 12 mechine and everything worked fine.

Then I built with:

```shell
$ cargo build --release --locked --no-default-features --features=native-tls
```

It was same with github release.

Then I tried:

```shell
$ cargo build --locked --no-default-features --features=native-tls
```

<details>
<summary>RUST_BACKTRACE=full</summary>

```shell
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 0 pages (0 orphan) and 0 sections
Done in 98ms.

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" })', src/cmd/serve.rs:437:59
stack backtrace:
   0:     0x55d78bf9abb1 - std::backtrace_rs::backtrace::libunwind::trace::he648b5c8dd376705
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55d78bf9abb1 - std::backtrace_rs::backtrace::trace_unsynchronized::h5da3e203eef39e9f
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d78bf9abb1 - std::sys_common::backtrace::_print_fmt::h8d28d3f20588ae4c
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55d78bf9abb1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd9a5b0c9c6b058c0
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55d78bfce0af - core::fmt::rt::Argument::fmt::h0afc04119f252b53
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/rt.rs:138:9
   5:     0x55d78bfce0af - core::fmt::write::h50b1b3e73851a6fe
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/mod.rs:1094:21
   6:     0x55d78bf960a7 - std::io::Write::write_fmt::h184eaf275e4484f0
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/io/mod.rs:1714:15
   7:     0x55d78bf9a9c5 - std::sys_common::backtrace::_print::hf58c3a5a25090e71
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55d78bf9a9c5 - std::sys_common::backtrace::print::hb9cf0a7c7f077819
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55d78bf9c1b3 - std::panicking::default_hook::{{closure}}::h066adb2e3f3e2c07
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:269:22
  10:     0x55d78bf9bf44 - std::panicking::default_hook::h277fa2776900ff14
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:288:9
  11:     0x55d78bf9c739 - std::panicking::rust_panic_with_hook::hceaf38da6d9db792
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:705:13
  12:     0x55d78bf9c637 - std::panicking::begin_panic_handler::{{closure}}::h2bce3ed2516af7df
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:597:13
  13:     0x55d78bf9b016 - std::sys_common::backtrace::__rust_end_short_backtrace::h090f3faf8f98a395
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:151:18
  14:     0x55d78bf9c382 - rust_begin_unwind
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
  15:     0x55d789e9a973 - core::panicking::panic_fmt::h4ec8274704d163a3
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
  16:     0x55d789e9af03 - core::result::unwrap_failed::h170bc2721a6c6ff2
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
  17:     0x55d789efc39c - core::result::Result<T,E>::unwrap::hc98fbe7e02ecc479
  18:     0x55d789f0d0e9 - zola::cmd::serve::serve::h8200e33f440a7bb0
  19:     0x55d789e9f334 - zola::main::h7fd1609447730de6
  20:     0x55d789f4df73 - core::ops::function::FnOnce::call_once::ha34ceacabe01e787
  21:     0x55d789eaf616 - std::sys_common::backtrace::__rust_begin_short_backtrace::h90565401460e3621
  22:     0x55d789ec9f59 - std::rt::lang_start::{{closure}}::hba66a7f0bed7f6ba
  23:     0x55d78bf8cf7b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h75ba4244a1c7bb54
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:284:13
  24:     0x55d78bf8cf7b - std::panicking::try::do_call::h0a2baa36dea975a1
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
  25:     0x55d78bf8cf7b - std::panicking::try::h0e42aa233d4224d4
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
  26:     0x55d78bf8cf7b - std::panic::catch_unwind::hefdfd8f482606434
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
  27:     0x55d78bf8cf7b - std::rt::lang_start_internal::{{closure}}::h457959f0f91da23b
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:148:48
  28:     0x55d78bf8cf7b - std::panicking::try::do_call::h112cfd1acb38183b
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
  29:     0x55d78bf8cf7b - std::panicking::try::ha64f15b20cec18ca
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
  30:     0x55d78bf8cf7b - std::panic::catch_unwind::hbacc2b68ee2c119e
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
  31:     0x55d78bf8cf7b - std::rt::lang_start_internal::h5f408694586c2a05
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:148:20
  32:     0x55d789ec9f37 - std::rt::lang_start::h3214fbcfe498180e
  33:     0x55d789e9fba5 - main
  34:     0x7fcf09e4624a - <unknown>
  35:     0x7fcf09e46305 - __libc_start_main
  36:     0x55d789e9b201 - _start
  37:                0x0 - <unknown>
```

</details>

**Comment by flyingicedragon** [comment]
Zola works now. I didn't do anything, not even restart my machine. It's so strange.

------

I met this problem again. This time I did nothing as last time. After about half an hour, zola works.
